name: FINAL_FIX_ULP
on:
  workflow_dispatch:

jobs:
  everything:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Start Everything
        run: |
          pip install pyTelegramBotAPI telethon
          python main.py
