name: FINAL_RUN
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run
        run: |
          pip install telethon pyTelegramBotAPI
          python main.py

