name: ULP Storm 24/7
on:
  schedule:
    - cron: '0 * * * *' # يخدم كل ساعة
  workflow_dispatch: # تشغيل يدويا

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install telethon
      - name: Run Scraper
        run: python main.py
      - name: Save Results
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add MEGA_STORM_ULP.txt
          git commit -m "Update ULP Logs" || exit 0
          git push
