name: AUTO_ULP_HUNTER

on:
  schedule:
    - cron: '0 * * * *' # يشتغل تلقائياً كل رأس ساعة
  workflow_dispatch: # يخليك تخدمو بيدك ثاني

jobs:
  hunter_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3 # يجيب ملفات main.py و session

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Packages
        run: |
          pip install telethon pyTelegramBotAPI

      - name: Start Harvesting
        run: python main.py # يبدأ الصيد والاستخراج
