name: ULP Storm & Bot 24/7
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install telethon pyTelegramBotAPI
      - name: Run Scraper and Bot
        run: |
          python main.py & # تشغيل السكربت في الخلفية
          python bot.py    # تشغيل البوت
      - name: Save Results
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add MEGA_STORM_ULP.txt
          git commit -m "Update ULP Logs from Bot" || exit 0
          git push
