name: SHOGHAL_ULP
on:
  workflow_dispatch:

jobs:
  run_everything:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start
        run: |
          pip install telethon pyTelegramBotAPI
          python main.py

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: scraped-urls
          path: ulp.txt
